name: spotify
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  hydrated_bloc:
  path_provider:
  flutter_bloc:
  firebase_core: ^2.24.2
  firebase_auth:
  get_it:
  dartz:
  equatable: ^2.0.5
  cloud_firestore:
  google_sign_in:


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Satoshi-Black.otf
    - assets/fonts/Satoshi-Bold.otf
    - assets/fonts/Satoshi-italic.otf
    - assets/fonts/Satoshi-Light.otf
    - assets/fonts/Satoshi-Medium.otf
    - assets/fonts/Satoshi-Regular.otf
    - assets/images/beel.png
    - assets/vectors/logo.png
    - assets/vectors/Moon.svg
    - assets/vectors/Sun.svg
    - assets/images/blackEllipse.png
    - assets/images/choosemodeBG.png
    - assets/images/rightdown.png
    - assets/images/righttop.png
    - assets/images/leftbackbtn.png
    - assets/images/billie.png
    - assets/images/rectangle.png
    - assets/images/Hide.png
    - assets/images/Line.png
    - assets/images/googleicon.png
    - assets/vectors/appleicon.svg
    - assets/images/Ellipse.png
    - assets/images/menu.png
    - assets/images/Next.png
    - assets/images/Pause.png
    - assets/images/Previous.png
    - assets/images/repeat.png
    - assets/images/shuffle.png
    - assets/images/up.png
    - assets/vectors/Heart.svg
    - assets/images/playerimage.png



  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.otf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.otf
          weight: 600
        - asset: assets/fonts/Satoshi-italic.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Light.otf
          weight: 300
        - asset: assets/fonts/Satoshi-Medium.otf
          weight: 500
        - asset: assets/fonts/Satoshi-Regular.otf
          weight: 400


