// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWNwLi3wzfnRUgAqD-Mm7E6ZcGO7GIkS4',
    appId: '1:1097367926092:web:440000345be96c1c4e0be9',
    messagingSenderId: '1097367926092',
    projectId: 'spotifyflutter-761b9',
    authDomain: 'spotifyflutter-761b9.firebaseapp.com',
    storageBucket: 'spotifyflutter-761b9.appspot.com',
    measurementId: 'G-6QSEPTESGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ8VU2LeEIA44j8TV5POSgadTelDJj6Pc',
    appId: '1:1097367926092:android:d541fc519684e63d4e0be9',
    messagingSenderId: '1097367926092',
    projectId: 'spotifyflutter-761b9',
    storageBucket: 'spotifyflutter-761b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_WqXao3CBVcYHSEw7eA0wgXYFQwpVIYg',
    appId: '1:1097367926092:ios:1ef0b77931e068474e0be9',
    messagingSenderId: '1097367926092',
    projectId: 'spotifyflutter-761b9',
    storageBucket: 'spotifyflutter-761b9.appspot.com',
    iosBundleId: 'com.application.spotify.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_WqXao3CBVcYHSEw7eA0wgXYFQwpVIYg',
    appId: '1:1097367926092:ios:1ef0b77931e068474e0be9',
    messagingSenderId: '1097367926092',
    projectId: 'spotifyflutter-761b9',
    storageBucket: 'spotifyflutter-761b9.appspot.com',
    iosBundleId: 'com.application.spotify.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWNwLi3wzfnRUgAqD-Mm7E6ZcGO7GIkS4',
    appId: '1:1097367926092:web:de9ccae69afedb644e0be9',
    messagingSenderId: '1097367926092',
    projectId: 'spotifyflutter-761b9',
    authDomain: 'spotifyflutter-761b9.firebaseapp.com',
    storageBucket: 'spotifyflutter-761b9.appspot.com',
    measurementId: 'G-M1QYCX6CGK',
  );
}
